flat_addins.Rmd:
  path: dev/flat_addins.Rmd
  state: active
  R: R/build_fusen_chunks.R
  tests: tests/testthat/test-build_fusen_chunks.R
  vignettes: []
  inflate:
    flat_file: dev/flat_addins.Rmd
    vignette_name: .na
    open_vignette: true
    check: false
    document: false
    overwrite: ask
flat_create_flat.Rmd:
  path: dev/flat_create_flat.Rmd
  state: active
  R: R/add_flat_template.R
  tests: tests/testthat/test-add_flat_template.R
  vignettes: []
flat_history_core.Rmd:
  path: dev/flat_history_core.Rmd
  R:
  - R/add_dev_history.R
  - R/fill_description.R
  - R/inflate.R
  tests:
  - tests/testthat/test-add_dev_history.R
  - tests/testthat/test-fill_description.R
  - tests/testthat/test-inflate-part1.R
  - tests/testthat/test-inflate-part2.R
  vignettes: vignettes/How-to-use-fusen.Rmd
flat_history_maintain.Rmd:
  path: dev/flat_history_maintain.Rmd
  R: []
  tests: []
  vignettes: vignettes/Maintain-packages-with-fusen.Rmd
flat_inflate_all.Rmd:
  path: dev/flat_inflate_all.Rmd
  state: active
  R: R/inflate_all.R
  tests: tests/testthat/test-inflate_all.R
  vignettes: vignettes/inflate-all-your-flat-files.Rmd
  inflate:
    flat_file: dev/flat_inflate_all.Rmd
    vignette_name: Inflate all your flat files
    open_vignette: false
    check: false
    document: true
    overwrite: 'yes'
flat_inflate_all_utils.Rmd:
  path: dev/flat_inflate_all_utils.Rmd
  state: active
  R:
  - R/inflate_all_utils.R
  - R/pre_inflate_all_diagnosis_eval.R
  tests:
  - tests/testthat/test-pre_inflate_all_diagnosis_eval.R
  - tests/testthat/test-inflate_all_utils.R
  vignettes: []
  inflate:
    flat_file: dev/flat_inflate_all_utils.Rmd
    vignette_name: .na
    open_vignette: false
    check: false
    document: true
    overwrite: 'yes'
flat_init_share_on_github.Rmd:
  path: dev/flat_init_share_on_github.Rmd
  state: active
  R: R/init_share_on_github.R
  tests: tests/testthat/test-init_share_on_github.R
  vignettes: vignettes/share-on-a-github-website.Rmd
flat_register_config_file.Rmd:
  path: dev/flat_register_config_file.Rmd
  state: active
  R: R/register_config_file.R
  tests: tests/testthat/test-register_config_file.R
  vignettes: vignettes/register-files-in-config.Rmd
  inflate:
    flat_file: dev/flat_register_config_file.Rmd
    vignette_name: Register files in config
    open_vignette: false
    check: false
    document: true
    overwrite: 'yes'
keep:
  path: keep
  R:
  - R/addins.R
  - R/create_fusen_rsproject.R
  - R/fusen-package.R
  - R/globals.R
  - R/inflate-utils.R
  - R/load_flat_functions.R
  - R/utils-pipe.R
  tests:
  - tests/testthat/test-create_fusen_rsproject.R
  - tests/testthat/test-inflate_qmd.R
  - tests/testthat/test-inflate_utils.R
  - tests/testthat/test-load_flat_functions.R
  - tests/testthat/test-skeleton.R
  vignettes: vignettes/tips-and-tricks.Rmd
